# Generated by Django 6.0.3 on 2026-03-15 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesai',
            name='slug',
            field=models.SlugField(default=1, max_length=250, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagesai',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='pagesai',
            name='time_create',
            field=models.DateField(auto_now_add=True, verbose_name='Create tim`e'),
        ),
        migrations.AlterField(
            model_name='pagesai',
            name='time_update',
            field=models.DateField(auto_now=True, verbose_name='Update_time'),
        ),
        migrations.AlterField(
            model_name='pagesai',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mainuser', verbose_name='User'),
        ),
    ]
