# Generated by Django 6.0.3 on 2026-03-15 09:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_pagesai_slug_alter_pagesai_name_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesai',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='Text_From_Ai_And_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_user', models.CharField(max_length=10000, verbose_name='Text_user')),
                ('text_ai', models.CharField(max_length=10000, verbose_name='Text_ai')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mainuser', verbose_name='User')),
            ],
        ),
    ]
