# Generated by Django 6.0.3 on 2026-03-15 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_alter_pagesai_slug_text_from_ai_and_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='text_from_ai_and_user',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='editor.pagesai', verbose_name='Chat'),
            preserve_default=False,
        ),
    ]
