# Generated by Django 6.0.3 on 2026-03-15 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_text_from_ai_and_user_chat'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_user', models.TextField(verbose_name='Text_user')),
                ('text_ai', models.TextField(verbose_name='Text_ai')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.pagesai', verbose_name='Chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mainuser', verbose_name='User')),
            ],
        ),
        migrations.DeleteModel(
            name='Text_From_Ai_And_User',
        ),
    ]
