# Generated by Django 6.0.3 on 2026-03-15 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_chatmessages_delete_text_from_ai_and_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessages',
            name='text_ai',
        ),
        migrations.AlterField(
            model_name='chatmessages',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='editor.pagesai', verbose_name='Chat'),
        ),
        migrations.AlterField(
            model_name='chatmessages',
            name='text_user',
            field=models.TextField(verbose_name='Text_ai'),
        ),
        migrations.AlterField(
            model_name='pagesai',
            name='time_create',
            field=models.DateField(auto_now_add=True, verbose_name='Create time'),
        ),
    ]
