# Generated by Django 6.0.3 on 2026-03-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0007_remove_chatmessages_text_ai_alter_chatmessages_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='text_ai',
            field=models.TextField(default=1, verbose_name='Text_ai'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessages',
            name='text_user',
            field=models.TextField(verbose_name='Text_user'),
        ),
    ]
