# Generated by Django 6.0.3 on 2026-03-16 09:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0008_chatmessages_text_ai_alter_chatmessages_text_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
